### ISSUE TITLE
download-duplicates [true/false] does not apply with filters

### ISSUE THREAD

**Issue by sibte** [autodl-community/autodl-irssi#100]
The setting "download-duplicates: [true/false]" does not apply as expected when multiple trackers (sites) are set on a filter. 

Expected: 
- The setting "download-duplicates: false" to prevent duplicates for all matches on filter, when set for a filter. 

Actual: 
- "download-duplicates: false" is overridden to only prevent matches per tracker (sites). 

Justification:
- It is counter-intuitive that setting "download-duplicates" to "false" on a filter should only apply for a tracker (site) only. The current functionality can easily be achieved by creating a filter with one tracker (site). Expected behaviour however, is not achievable without 3rd party solutions. 

Possible solutions:
- change "download-duplicates" functionality to respect all matches for filter. The current functionality can then easily be achieved by creating a filter with only one tracker (site). 
- change "download-duplicates" setting and functionality so values can be set to: [true,false,filter,tracker].

I would vote for option 1, as it should be easier to implement and behaves as expected. 

Versions:
autodl-irssi v1.61, autodl-trackers v253

**Comment by thebigmunch** [comment]
The setting is not tied to tracker at all.

To be clear, ``download-duplicates = False`` would prevent the download of the same release (read: release name), not just the same season/episode combo or the like. In the same vain, if trackers somehow end up with different release names for the same release, it wouldn't work.

Those are the two more common ways that people think download-duplicates isn't working properly. Also worth noting, make sure ``save-download-history`` isn't set to false, and ``max-saved-releases`` is set high enough (defaults to 1000).

**Comment by sibte** [comment]
My apologies then, I could not find any documentation confirming that behavior, nor could I find any other viable bug in the configuration to suggest otherwise when going through the logs several times. I can however confirm that "save-download-history" is indeed set to "true", "max-save-releases" is set to "1000" and that there are several equal releases (as in name). I'll reinvestigate my logs again, might be the usage of "match-releases" vs "shows" that produce different possible matches. Thanks

**Comment by thebigmunch** [comment]
Do you happen to have ``download-duplicates`` set to true in the options header?

**Comment by thebigmunch** [comment]
Closing due to lack of response. Please post a comment if any further information is gathered.

**Comment by ne0ark** [comment]
There is something definitely wrong with download duplicate. For some reason that option keeps getting unchecked.
