### ISSUE TITLE
Order of filters affects how it filters

### ISSUE THREAD

**Issue by plitter** [autodl-community/autodl-irssi#104]
http://sprunge.us/HjiT
This is the filters I've been using for a while. btn_tv filter should have matched the elementary torrent that is displayed on top, but it didn't. It did so before I added the btn_snatch. After I moved btn_snatch above btn_tv it starts working again.

**Comment by thebigmunch** [comment]
You should check out the wiki. But that's all I'm going to say, because I don't provide support for people farming.
