### ISSUE TITLE
Irssi:  ERROR:  Exception in onPrivmsg: Quantifier follows nothing in regex; marked by <-- HERE in m/* <-- HERE Prologe*/ at ~/.irssi/scripts/AutodlIrssi/FilterManager.pm line 193.

### ISSUE THREAD

**Issue by GerardGarcia** [autodl-community/autodl-irssi#105]
The error appears every few minutes. 

Using latest version installed two days ago following manual installation.

**Comment by thebigmunch** [comment]
Post your filters.

**Comment by GerardGarcia** [comment]
[filter The Simpsons]
match-sites = btn
shows = The Simpsons
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/The Simpsons/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-categories = Episode
except-tags = Foreign*
except-releases = *-TOPKEK

[filter Family Guy]
match-sites = btn
shows = Family Guy
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Family Guy/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-categories = Episode
except-tags = Foreign*
except-releases = *-TOPKEK

[filter The Walking Dead]
match-sites = btn
shows = The Walking Dead
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/Others/Edu
upload-type = rtorrent
match-categories = Episode
except-tags = Foreign*
except-releases = *Prologe*
max-downloads = 1
use-regex = true
max-downloads-per = week
rt-label = Edu

[filter Modern Family]
match-sites = btn
shows = Modern Family
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Modern Family/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-categories = Episode
except-tags = Foreign*
except-releases = *-TOPKEK

[filter How I met your mother]
match-sites = btn
shows = How I met your mother
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/How I met your mother/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
except-releases = Ntb
match-categories = Episode
except-tags = Foreign*

[filter The Big Bang Theory]
match-sites = btn
shows = The Big Bang Theory
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/The Big Bang Theory/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-releases = *-DIMENSION
match-categories = Episode
except-tags = Foreign*

[filter American Dad]
match-sites = btn
shows = American Dad
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/American Dad/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
except-tags = Foreign*

[filter Game of Thrones]
match-sites = btn
shows = Game of Thrones
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Game of Thrones/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-releases = *-EVOLVE
match-categories = Episode
except-tags = Foreign*
except-releases = *-PiratesZone, *-Coveiro

[filter The Cleveland Show]
match-sites = btn
shows = The Cleveland Show
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/The Cleveland Show/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-categories = Episode
except-tags = Foreign*

[filter South Park]
match-sites = btn
shows = South Park
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/South Park/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-categories = Episode
except-tags = Foreign*

[filter Ridiculousness]
match-sites = btn
shows = Ridiculousness
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Ridiculousness/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
match-categories = Episode
except-tags = Foreign*
match-releases = *-YesTV

[filter Bobs Burgers]
match-sites = btn
shows = Bobs Burgers
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Bobs Burgers/Season $(Season)
upload-type = rtorrent
rt-dont-add-name = true
except-tags = Foreign*
except-releases = *-TOPKEK
enabled = false

[filter _BTN]
match-sites = btn
min-size = 100MB
max-size = 2GB
max-downloads = 4
rt-dir = /home/disk3/xeri/torrents/shares/TV
rt-label = BTN 1week
upload-type = rtorrent
max-downloads-per = day
resolutions = 720p
rt-ratio-group = rat_7
enabled = false

[filter _PTP]
match-sites = ptp
max-size = 3GB
max-downloads-per = day
rt-dir = /home/disk3/xeri/torrents/shares/Movies
rt-ratio-group = rat_6
upload-type = rtorrent
rt-dont-add-name = true
years = 2004-2012
freeleech = true
encoders = DivX, h.264, x264, XviD
rt-label = PTP Freeleech!
min-size = 650MB
max-downloads = 10
enabled = false

[filter Homeland]
match-sites = btn
shows = Homeland
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Homeland/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
match-categories = Episode
except-tags = Foreign*
enabled = false

[filter Archer 2009]
match-sites = btn
shows = Archer 2009
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Archer 2009/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
except-tags = Foreign*

[filter _WHAT]
max-size = 100MB
formats = MP3
max-downloads = 4
max-downloads-per = day
match-sites = what
rt-dir = /home/disk2/xeri/torrents/shares/Music/_auto
rt-label = Music auto
upload-type = rtorrent
except-releases = *V0*,*V1*,*V2*,*deutsch*,*swedish*,*german*,*french*,*spanish*,*greek*,*italian*,*danish*,*dansk*,*finnish*,*norwegian*,*turkish*,*arabic*,*chinese*,*korean*,*thai*,*russian*,*canadian*,*sampler*,*promo*,*demo*,*soundtrack*,*Ç*,*ğ*,*さ*,*よ*,*な*,*ら*,*フ*,*ロ*,*ン*,*テ*,*ィ*,*ア*,*æ*,*ø*,*å*,*ö*,*ä*,*ğ*,*ş*,*ü*,*Ş*,*命*,*中*,*注*,*定*,*最*,*犀*,*利*,*命*,*中*,*注*,*定*,*最*,*犀*,*利*,*》*,*影*,*視*,*主*,*題*,*曲*,*給*,*力*,*大*,*合*,*輯*,*î*,*北*,*原*,*沙*,*弥*,*香*,*か*,*な*,*り*,*純*,*情*,*이*,*바*,*디*,*ğ*,*ş*,*ü*,*л*,*ь*,*к*,*д*,*л*,*я*,*в*,*и*,*Ž*,*ž*,*ć*,*ë*,*ú*,*á*
years = 2013
except-tags = *bandcamp*,*cpop*,*korea*,*chinese*,*norwegian*,*synth.pop*,*dub.techno*,*edm*,*moderncreative*,*freejazz*,*japan*,*portugal*,*italy*,*atmospheric*,*soundscape*,*heavy*,*goth*,freely.available,*canadian*,*Canadian*,*Progressive*,*progressive*,*Folk*,*folk*,*chamber*,spiritual,*fusion*,n.y,*goa*,hardcore.rap,*melodic*,*italian*,electro.house,lo.fi,*mashup*,*trap*,*groove*,djent,tzadik,*acid*,*deep*,*Celtic*,*twee*,*thrash*,*sleaze*,*irish*,*power*,*crunk*,*holiday*,*christmas*,*instrumental*,*island*,*psychedelic*,fast.food,waffle.house,*jukebox*,*casio*,leeds,*indie*,*leeds*,thethirdperson,*detroit*,*Kentucky*,*Drag*,City,*Opera*,*opera*,*jrock*,*japan*,*australia*,*black*,kpop,gothic,*canada*,*trance*,*baroque*,*future*,*americana*,*alternative*,*industrial*,*art*,*polydor*,*post*,*punk*,*gabber*,*speedcore*,*experimental*,*neo*,*psychedelia*,*space*,*swiss*,*crust*,tech.house,*bluegrass*,*ritual*,*drone*,*anime*,kansas.city,power.eletronics,free.jazz,*dutch*,jazz.rock,*mexico*,*hair*,*stoner*,*train*,old.time,*abstract*,*dark*,*ambient*,*shamanic*,*russian*,*noise*,*christian*,*numetal*,*eastern*,*effects*,*processed*,*glitch*,*funk*,*violin*,*hardstyle*,big.band,*swing*,*musical*,*revelation*,nyhc,*poland*,*polish*,*yass*,free.jazz,*shoegaze*,*french*,nu.jazz,*latin*,*sludge*,*mkmetal*,*macedonia*,*serbian*,*metalcore*,*screamo*,*downtempo*,*martial*.*urban*,world.music,*vanity*,*garage*,ska,*minimal*,new.age,*hardcore*,*jpop*,idm,emo,*country*,*classical*,*turkish*,*comedy*,*listening*,bossa.nova,*brazil*,1920s,1930s,1940s,1950s,1960s,1970s,1980s,blue.grass
bitrates = 320
enabled = false

[filter Vice]
match-releases = *-2hd, *-EVOLVE
shows = Vice
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Vice/Season $(Season)
upload-type = rtorrent
match-sites = btn
match-categories = Episode
except-tags = Foreign*

[filter Shingeki no Kyojin]
rt-dir = /mnt/media/Anime/Attack on Titan
rt-dont-add-name = true
upload-type = rtorrent
match-sites = btn
match-releases = HorribleSubs
shows = Shingeki no Kyojin
resolutions = 720p
sources = WEB-DL

[filter Under THe Dome]
match-sites = btn
shows = Under The Dome
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Under The Dome/Season $(Season)
upload-type = rtorrent
match-releases = *-DIMENSION
rt-dont-add-name = true
enabled = false

[filter Naruto shippuuden]
match-sites = btn
rt-dir = /mnt/media/Anime/Naruto Shippuuden
upload-type = rtorrent
max-size = 500MB
match-releases = .*HorribleSubs.*Naruto.Shippuuden.*720p.*
use-regex = true

[filter Brickleberry]
match-sites = btn
shows = Brickleberry
resolutions = 720p
sources = WEB-DL
rt-dir = /mnt/media/TV/Brickleberry/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent

[filter Rick and Morty]
match-sites = btn
shows = Rick and Morty
resolutions = 720p
sources = WEB-DL
rt-dir = /mnt/media/TV/Rick and Morty/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent

[filter Regular Show]
match-sites = btn
shows = Regular Show
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Regular Show/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
enabled = false

[filter Black Sails]
match-sites = btn
shows = Black Sails
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Black Sails/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
except-releases = *DD5.1*, *-NTb
enabled = false

[filter True Detective]
match-sites = btn
shows = True Detective
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/True Detective/Season $(Season)
upload-type = rtorrent
match-release-groups = killers, 2hd, 0sec, BATV
except-release-groups = NTb, novamedia

[filter Brooklyn Nine-Nine]
match-sites = btn
shows = Brooklyn Nine-Nine
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Brooklyn Nine-Nine/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
except-releases = *-TOPKEK

[filter Vikings]
match-sites = btn
shows = Vikings
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Vikings/Season $(Season)
upload-type = rtorrent

[filter Cosmos]
match-sites = btn
shows = Cosmos
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Cosmos/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent

[filter Resurrection]
match-sites = btn
shows = Resurrection
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Resurrection/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
enabled = false

[filter Silicon Valley]
match-sites = btn
shows = Silicon Valley
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Silicon Valley/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
except-releases = *-NTb, *-NorTV

[filter Better Call Saul]
match-sites = btn
shows = Better Call Saul
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Better Call Saul/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent

[filter Major Lazer]
match-sites = btn
rt-dir = /mnt/media/TV/Major Lazer/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
shows = Major Lazer
match-releases = DIMENSION
resolutions = 720p
sources = HDTV

[filter Mr. Robot]
match-sites = btn
shows = Mr Robot
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Mr. Robot/Season $(Season)
rt-dont-add-name = true
upload-type = rtorrent
match-release-groups = KILLERS, DIMENSION

[filter Draogn Ball Super]
match-sites = btn
rt-dir = /mnt/media/Anime/Dragon Ball Super
upload-type = rtorrent
shows = Dragon Ball Super
match-releases = .*Dragon.Ball.Super.*
use-regex = true

[filter Gotham]
match-sites = btn
shows = Gotham
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Gotham/Season $(Season)
upload-type = rtorrent
enabled = false

[filter One-Punch Man]
match-sites = btn
rt-dir = /mnt/media/Anime/One Punch Man/
upload-type = rtorrent
match-releases = .*HorribleSubs.*One-Punch.Man.*720p.*
use-regex = true

[filter Fargo]
match-sites = btn
shows = Fargo
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Fargo/Season $(Season)
upload-type = rtorrent

[filter The Knick]
match-sites = btn
shows = The Knick
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/The Knick/Season $(Season)
upload-type = rtorrent

[filter Ash vs Evil Dead]
match-sites = btn
shows = Ash vs Evil Dead
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/Ash vs Evil Dead/Season $(Season)
upload-type = rtorrent

[filter The Expanse]
match-sites = btn
shows = The Expanse
resolutions = 720p
sources = HDTV
rt-dir = /mnt/media/TV/The Expanse/Season $(Season)
upload-type = rtorrent

Maybe because of the _WHAT filter although it is disabled?

**Comment by thebigmunch** [comment]
No, the error you posted be caused by the particular filter I left in your comment. If you removed use-regex (you don't actually seem to use it anyway), you would no longer get the error. Unfortunately, BTN is down, so you can't really test it right now. I'll try to replicate and fix whatever might be causing it if I can anyway.
