### ISSUE TITLE
autodl with unix sockets is broken for rtorrent

### ISSUE THREAD

**Issue by genghizkhan91** [autodl-community/autodl-irssi#108]
This is a duplicate of issue #77, but I thought I'd start a new issue for it because the previous one has been closed.

**Summary:** So autodl works perfectly when one uses a TCP socket for rtorrent RPC communication. However, once one switches to a unix domain socket, then rutorrent and rtorrent work together perfectly, as expected, but autodl doesn't. If I set the action upon completion to "rtorrent", it basically reports that it's sent the torrent to rtorrent (like it does with a TCP socket) but rtorrent never adds the torrent to the download queue. Sending torrent files to a watch folder works fine.

**Relevant details:** rtorrent is running as the user `rtorrent` and the group `http`. irssi is running as the user `rtorrent` and group `http`. The unix socket is created in `/run/rtorrent/rpc.socket` with permissions `0770`, and the directory `rtorrent` is owned by `rtorrent:http`. The relevant details of my .rtorrent.rc are:

```
scgi_local = /run/rtorrent/rpc.socket
xmlrpc_dialect=i8
```

and my .autodl/autodl2.cfg reads:

```
[options]
rt-address = /run/rtorrent/rpc.socket
```

**Comment by thebigmunch** [comment]
You should've posted this information in the other issue. Closing as duplicate.
