### ISSUE TITLE
Autodl not downloading even when monitoring

### ISSUE THREAD

**Issue by rahul0705** [autodl-community/autodl-irssi#109]
I created an automatic install for autodl-irssi and rutorrent. After configuring my auto install to create the correct config file and have the system up and running (monitoring does show up in the logs) I still am not able to get a match (unless the filter is set to *)

    [options]
    update-check = auto
    upload-type = rtorrent
    rt-label = scene
    gui-server-port = <removed>
    gui-server-password = <removed>
    rt-ratio-group = rat_0
    output-level = 100
    debug = true
    advanced-output-sites = <removed>

    [irc]
    close-nickserv = true

    [webui]

    [ftp]

    [server <removed>]
    port = <removed>
    ssl = true
    nick = <removed>
    ident-password = <removed>
    ident-email = rahul0705@gmail.com

    [channel <removed>]
    name = <removed>

    [filter Suits]
    match-sites = ar, dh, scc, tl
    shows = Suits
    seasons = 1-10000
    episodes = 1-10000
    resolutions = SD
    encoders = x264
    sources = HDTV

This caused a nothing to be matched even though this was what was parsed:

    <removed> : canonicalizedName: 'suits s05e06 hdtv x264 killers' : category: 'TvSD' : encoder: 'x264' : episode: '6' : name1: 'Suits' : preTime: '3 minutes 42 seconds' : season: '6' : site '<removed>' : source: 'HDTV' : torrentName: 'Suits.S06E06.HDTV.x264-KILLERS' : torrentUrl : <removed> : $baseUrl: <removed> : $torrentId: <removed>

I am not sure why these are mot matching.

**Comment by thebigmunch** [comment]
Use the IRC channel for support.
