### ISSUE TITLE
SD releases can't be downloaded if not explicitly in the Announce

### ISSUE THREAD

**Issue by rahul0705** [autodl-community/autodl-irssi#110]
with filter:

    [filter Suits]
    match-sites = <removed>
    shows = Suits
    seasons = 1-10000
    episodes = 1-10000
    resolutions = SD
    encoders = x264
    sources = HDTV

there is not match with:

    <removed> : canonicalizedName: 'suits s05e06 hdtv x264 killers' : category: 'TvSD' : encoder: 'x264' : episode: '6' : name1: 'Suits' : preTime: '3 minutes 42 seconds' : season: '6' : site '<removed>' : source: 'HDTV' : torrentName: 'Suits.S06E06.HDTV.x264-KILLERS' : torrentUrl : <removed> : $baseUrl: <removed> : $torrentId: <removed>

In the original release of autodl this would match for SD. It seems that if the release is implicitly SD (lack of resolution) it wont set the resolution value to SD. While if it is there it will:

    <removed>  : canonicalizedName: 'mr robot s02e07 1080p hdtv x264 brisk' : category: 'TV-HD' : encoder: 'x264' : episode: '7' : name1: 'Mr Robot' : resolution: '1080p' : season: '2' : site: '<removed>' : source: 'HDTV' : torrentName: 'Mr.Robot.S02E07.1080p.HDTV.x264-BRISK'

Seems like these lines got cut from the original release in AnnounceParser.pm:extractReleaseNameInfo

    if ($isTvOrMovie && !$out->{resolution}) {
        $setVariable->("resolution", "SD");
    }

**Comment by thebigmunch** [comment]
This was a deliberate change, and there are other issues already where you can get more information surrounding it.
