### ISSUE TITLE
HTTP 3xx redirects unsupported, trigger download error

### ISSUE THREAD

**Issue by mcginty** [autodl-community/autodl-irssi#112]
when `force_ssl` is `true` for PTP, it looks like autodl isn't willing to follow redirects (I'm guessing since https://passthepopcorn.me redirects to https://tls.passthepopcorn.me).

```
21:12 -!- Irssi:  ERROR:  Got HTTP 302, check your tracker settings for PassThePopcorn! Torrent: [whatever]
```

**Comment by GunsAkimbo** [comment]
How about modifying the .tracker file to include the tls-subdomain for the download url?

**Comment by thebigmunch** [comment]
Also, closing because tracker issues belong on the autodl-trackers repository. Post there if still necessary.
