### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by Eylandt** [autodl-community/autodl-irssi#114]
If I got autodl-irssi loaded and I quit irssi then I get segmentation fault: 11 error in terminal every time. If I remove autodl-irssi from autorun and quit irssi then I don't get that error.

OSX 10.11.6
autodl-irssi: v1.62
irssi: v0.8.19

**Comment by qrx** [comment]
Eylandt, I'm having the same issue. How did you fix it?
