### ISSUE TITLE
Resetting download count?

### ISSUE THREAD

**Issue by jacobslusser** [autodl-community/autodl-irssi#115]
Apologies if this has already been asked/answered but I didn't find anything related to this question in the issues list and my weak understanding of Perl gave me no help from the source code either...

Is there a way to 'reset' the max downloads so that the count will start over?

The use case is that I might have a filter set for '1 download per forever'... and the filter matches on the incorrect item. I adjust the filter but would like to still only try '1 download per forever'. My current understanding is that the filter criteria has been met (even though I've changed the matching logic) and it will not try to download again.

Is this correct? If so, is there a way to reset the count so that it will try to download again? Would an alternative be to bump the max downloads to '2'? That would work for a 'forever' filter but would be less effective for a recurring one...

Thanks.

**Comment by thebigmunch** [comment]
Quick and easy way is to rename the filter. You can also shut down autodl-irssi and change the AutodlState.xml file accordingly.

**Comment by thebigmunch** [comment]
PS Please use IRC for help and support. The Issue Tracker is for bugs and feature requests.
