### ISSUE TITLE
Duplicates are now coming through

### ISSUE THREAD

**Issue by BigEd01** [autodl-community/autodl-irssi#116]
Could figure out why until now. Version 1.62 is ignoring duplicates. 1.61 stopped them
ie: 
showname.s01e01.720p.HDTV-releasegroup
showname s01e01 720p HDTV releasegroup

Neither of the sites I grab from have changed anything. My old seedbox was doing great and that had 1.61. New seedbox with fresh load ended up with 1.62 and is now ignoring the spaces, period, dashes in the names. Like I said, going back for months in the logs and the announce channels havent changed and I just started usinf 1.62 past 2 days.

**Comment by thebigmunch** [comment]
It's more likely related to #106 than autodl-irssi version. It's just a rare case. Nothing changed between 1.61 and 1.62 with release name comparison for duplicates.

**Comment by BigEd01** [comment]
This sounds like a better understanding of the problem and what is happening to me. Out of 3 sites I monitor I am always getting a few duplicates a night causing mayhem because of slightly different sfv and or nfo files and all of them erring out as mismatched. I'll have to cut off the least 2 sites until this can be addressed.  I guess this can be closed at this point.
