### ISSUE TITLE
Error in Screen irssi

### ISSUE THREAD

**Issue by meskafonas** [autodl-community/autodl-irssi#119]
**Please read the contributing guidelines linked above before opening an issue.**
I installed Irssi and if choose `screen -S autodl -fa -d -m irssi` in command line it gives somes errors. Should i be worried about that? :) Screenshot in the link:  https://i.imgbox.com/g5Qf0tGL.png

**Comment by thebigmunch** [comment]
That shows you have an error in your irssi config, which has nothing to do with autodl-irssi.
