### ISSUE TITLE
Messages that no one should see

### ISSUE THREAD

**Issue by m0021a** [autodl-community/autodl-irssi#120]
Hello,
two days ago, I downloaded autodl-irssi. When I set all in my ruTorrent 3.6 properly, I ran irssi. Script autodl loaded ok, everything was fine until I entered to the #announce channel. Script autodl every time the public informed of all what I download, or show the information when I saved settings. From what I know, it should not be.  I went to another channel and messages that seemed script autodl began to annoy people and I was kick out of the channel. Just look at screenshot. 

![11](https://cloud.githubusercontent.com/assets/24656940/21322414/34a9db60-c619-11e6-81da-48d19c649f6d.png)

@thebigmunch

**Comment by thebigmunch** [comment]
Those messages are not output to IRC unless you set up the IRC output. Looks like you did that mistakenly.

**Comment by m0021a** [comment]
I'm fighting with the script second or third day, and still do not know what's going on.
