### ISSUE TITLE
Error in Smart Episode season-episode conditional

### ISSUE THREAD

**Issue by grayshirt** [autodl-community/autodl-irssi#121]
Filters with Smart Episode enabled are incorrectly matching new torrents of the form S##E## where the episode number is greater than the most recently matched without regard to the season number. For example, "Television.Show.S11E05" will be downloaded even if "Television.Show.S12E04" has already been matched.

The error appears to be in the condition tested on line 104 of [MatchedRelease.pm](https://github.com/autodl-community/autodl-irssi/blob/devel/AutodlIrssi/MatchedRelease.pm):

    if ($ti->{season} <= $state->{smart}{season} && $ti->{episode} <= $state->{smart}{episode}) {

I believe adding the condition:

    if ($ti->{season} < $state->{smart}{season})

somewhere before or in conjunction with this test and modifying the above to test only for episode number when the seasons match would achieve the desired behavior, but I do not write code this in this language and wasn't sure what the preferred convention was so I didn't want to submit a pull request.

**Comment by thebigmunch** [comment]
Thanks. I'll put out an update sometime soon.

> I do not write code this in this language

Nobody does. We just write a jumbled mess that somehow does something. It's pretty awful : P
