### ISSUE TITLE
Support list of comma separated values on separate lines in autodl.cfg

### ISSUE THREAD

**Issue by dashbad** [autodl-community/autodl-irssi#122]
I have a filter for "shows" with a large number of shows and I get a config error if I try and separate the list of shows on separate lines. e.g.:

Current: movie1,movie2,movie3,movie4

Desired: movie1,
               movie2,
               movie3,
               movie4

This would be useful for readability

Is this possible or implementable?

**Comment by thebigmunch** [comment]
Frankly, readability is best served by using separate filters for separate titles.

It's possible, but I'm not likely to spend any time on it. I could certainly help someone get started if they wanted to take a crack at it, though.

**Comment by PaulBags** [comment]
Are there other ways this could be done which would be less problematic to implement, say one [filter] with multiple 'show =' lines? Or maybe have [filter-rules-group <name>] and [filter group=<name>]? Basically anything that would reduce multiple size, delay, etc lines that are the same?
