### ISSUE TITLE
Prefer Higher Resolution Match Option

### ISSUE THREAD

**Issue by jmdevince** [autodl-community/autodl-irssi#129]
When specifying resolutions for TV/Movies, allow for logic that will only download the release if it's a higher resolution than the last release for the same show / season / episode that was downloaded. This way initial qualities can be downloaded and then ramped up based on the allowed downloaded resolutions.

At the same time this would prohibit a higher resolution being trumped by a lower resolution.

**Comment by thebigmunch** [comment]
This is outside the scope of the filters in autodl-irssi. You can, however, script the behavior you want and use the ``exec`` action.
