### ISSUE TITLE
Duplicate and SSL not staying checked

### ISSUE THREAD

**Issue by skylinekiller** [autodl-community/autodl-irssi#130]
After I check (enable) the duplicate option and the SSL option and save it and then open it back up, the checks do not appear on some filters, but on some they are still there.  I downloaded the .cfg and it shows "true" for duplicates, but they are not checked when I open up the filter tab.

Is there a fix for this?

I am using autodl-irssi 1.64|autodl-trackers v263 in Rutorrent

**Comment by thebigmunch** [comment]
This is an autodl-rutorrent issue, not autodl-irssi, that was fixed. See [here](https://github.com/autodl-community/autodl-rutorrent/issues/26). You'd have to check your ruTorrent plugin version, not autodl-irssi, to see if you're up-to-date.
