### ISSUE TITLE
don't download torrent when using run program action

### ISSUE THREAD

**Issue by cwallace** [autodl-community/autodl-irssi#131]
I'm utilizing this simple shell script to push releases to sonarr:

https://github.com/Zymest/autodl-curl-sonarr

The script simply sends the release name, download url and api key to sonarr. Sonarr then determines if it wants the release and does its magic from there. However, autodl-irssi is still downloading the torrent for each matched release. Since I'm pushing all releases in the TV category this is unnecessarily downloading a huge amount of torrents from all of my trackers. Could we add an option to the "Run Program" action to skip downloading the torrent?

**Comment by thebigmunch** [comment]
No. Special-casing something to not download for a program built for the purpose of downloading doesn't really make sense.

You'd probably want to ask for local file support to be added to Sonarr instead, if it doesn't already support it without documenting it. That way you could simply specify the torrent file as downloaded by autodl-irssi as the ``downloadUrl`` in the Sonarr API call. It seems like a reasonable feature.
