### ISSUE TITLE
feature suggestion: clone a filter

### ISSUE THREAD

**Issue by baz357** [autodl-community/autodl-irssi#135]
Instead of always having to start from zero with a new filter, wouldn't it be great if one could just clone an existing filter and just edit it a bit?

Thanks to everyone working on autodl-irssi!

**Comment by thebigmunch** [comment]
Sorry for not responding for so long, busy time.

This should be posted on the [ruTorrent plugin](https://github.com/autodl-community/autodl-rutorrent) issue tracker instead. This wouldn't be implemented in autodl-irssi itself; you can just copy/paste in the autodl.cfg file for that.
