### ISSUE TITLE
Iptorrents autodl

### ISSUE THREAD

**Issue by P4R4DiSi4C** [autodl-community/autodl-irssi#136]
Hello,

I can't seem to get iptorrents working...
Here is the errors:
[https://vgy.me/YcTqUX.png](url)

Here is how I tried to set the cookie:
[https://vgy.me/PvAKJ3.png](url)

I have the latest  version of autodl

Thank you very much

**Comment by thebigmunch** [comment]
The issue tracker is for bugs and feature requests, not support.
