### ISSUE TITLE
Request: easily set alt nick to use

### ISSUE THREAD

**Issue by pleasedontbecrap** [autodl-community/autodl-irssi#137]
Can we get an easy way to set alt nick if nick is taken due ghosting? Preferably with checking to return to proper nick when ghost disappears? a1todl autonaming is a pain.

Or can we do this already by using multiple nick lines in the server block? Autodl doesn't throw up an error configured this way, but I don't want to run the risk. If it's just undocumented then sweet, could we get the wiki updated?

**Comment by thebigmunch** [comment]
Well, it's not autodl-irssi that does the autonaming, irssi itself does. irssi has an ``alternate_nick`` setting. The docs don't show it can be used as part of the ``/connect`` command, just set separately and globally.

As for setting the nick twice in a server block, autodl-irssi would just use the last defined nick.
