### ISSUE TITLE
RTT now has an #announce channel for regular users.

### ISSUE THREAD

**Issue by i-am-eny0** [autodl-community/autodl-irssi#141]
RTT (RevolutionTT) now operates an #announce channel for non-VIP users with a 5-minute delay.
The output is as follows:

`<RevoTT> !new RLS.NAME | CATEGORY | https://revolutiontt.me/details.php?id=XXXXXXX&hit=`1

Would love to see an update to the trackers file to reflect this :)

**Comment by thebigmunch** [comment]
The crackers have a separate repo. And there is already an issue for that: https://github.com/autodl-community/autodl-trackers/issues/214
