### ISSUE TITLE
Removing the allowed option

### ISSUE THREAD

**Issue by thebigmunch** [autodl-community/autodl-irssi#142]
I'd like to know if anyone has any **good**, **valid** reasons for using the ``allowed`` option to restrict torrent actions for users. This is in anticipation of removing the option and ``/etc/autodl.cfg``.

**Comment by ashmandias** [comment]
As a user, I would personally avoid any provider that disallows any features of autodl. That implies that they are either hiding something, or don't know how to properly secure a box -- or arbitrarily decided to disallow shell access -- none of which are good signs.
