### ISSUE TITLE
autodl-irssi fails to match other downloads when they win the delay.

### ISSUE THREAD

**Issue by KyleSanderson** [autodl-community/autodl-irssi#144]
Not sure where the bug is ....

18:54 -!- Irssi: Matched Brooklyn.Nine-Nine.S05E11.1080p.WEB.x264-TBS in TV/X264, 820.46 MB (Television-HDTV), pre'd 48 seconds ago, GFTracker
18:54 -!- Irssi: Waiting 600 seconds. Torrent Brooklyn.Nine-Nine.S05E11.1080p.WEB.x264-TBS, GFTracker
19:04 -!- Irssi: Sent torrent to rtorrent Brooklyn.Nine-Nine.S05E11.1080p.WEB.x264-TBS, GFTracker, total time 600.565 seconds

18:55 <@Barney> NOW BROADCASTING! [ Brooklyn.Nine-Nine.S05E11.1080p.WEB.x264-TBS ]
18:55 <@Barney> [ Title: S05E11 ] [ Series: Brooklyn Nine-Nine ]
18:55 <@Barney> [ 2017 ] [ Episode ] [ MKV | H.264 | WEB-DL | 1080p | Scene | FastTorrent ] [ Uploader: AutoUp ]...

18:54 < _AnnounceBot_> New Torrent Announcement: <TV :: Episodes HD>  Name:'Brooklyn Nine-Nine S05E11 1080p WEB x264-TBS' uploaded by 'Anonymous' -...

18:55 <@tehDude> tehFIRE: [TV|x264] Brooklyn.Nine-Nine.S05E11.1080p.WEB.x264-TBS 
18:54 < Voyager> [New Release]-[TvHD]-[Brooklyn.Nine-Nine.S05E11.1080p.WEB.x264-TBS]-[URL]-...

GFT is my least priority because of corrupt/incomplete downloads, but it keeps winning out. I'm not certain if there's a bug with the match or what's going on, but there's a definite issue with what's current in autodl-irssi as everything else matches when GFT doesn't win. There's 3 other trackers in the list where they have a higher priority as well to what's listed.

**Comment by thebigmunch** [comment]
Please come to the support channel until you actually know that something is a bug.

**Comment by KyleSanderson** [comment]
Confirmed. This is a regression from https://github.com/autodl-community/autodl-irssi/issues/106 / https://github.com/autodl-community/autodl-irssi/commit/764cc58a348db6307583e7ea22512e33667831cd . Reverting instantly fixes this.

**Comment by KyleSanderson** [comment]
To clarify what the issue is incase there's any confusion, you're now calling $self->_addDownload(); and then waiting for $self->_onTorrentUploadWait(); the timer to hit. Before this feature was there to allow other trackers to win, and supersede others. Adding the download history and then waiting is causing this to show as something already snatched; and thus the regression.

**Comment by ashmandias** [comment]
Do you have any filters to post as an example? What did the folks on IRC have to say about this issue?

**Comment by KyleSanderson** [comment]
Didn't ask on IRC, my setup has been the same since alpha testing this on SCC what feels like a decade ago now.

Example is pretty darn easy, announce from one site with a tracker delay, have another tracker pre, autodl-irssi as of commit https://github.com/autodl-community/autodl-irssi/commit/764cc58a348db6307583e7ea22512e33667831cd will ignore the line because it's already added to the download history. Previous expected behaviour is the new line takes over, delay hits, and then, finally, whomever wins; uploads to your favourite torrent client.

If you're looking for a decent config, have at it.
```
[filter Television-HDTV]
shows = 
match-sites = 
match-categories = TV-HD, TV/X264, TV/HD-X264, TvHD, Seriale HD, TV :: Episodes HD, TV|x264, Episode
upload-type = rtorrent
#upload-type = exec
upload-command = /usr/bin/deluge-console
upload-args = add -p "/mnt/Television/$(Show)" "$(TorrentPathName)"
rt-dir = /mnt/Television/$(Show)
rt-commands = print="Added: $(TorrentName)"
rt-label = Tele-$(TrackerShort)-$(Show)
rt-priority = high
encoders = x264, H.264, h264, x264-Hi10p
min-size = 125MB
max-size = 6.5GB
sources = HDTV, WEBRip, WEB, WEB-DL
resolutions = 720p, 1080p, 2160p
except-releases = *Rus.Eng*, *.GERMAN.*, *-DUAL*, *.DUAL-*, *MULTi*, *FLEMISH*, *SWEDiSH*, *.NL.*, *.DL.*, *DUBBED*, *SPANiSH*, *DANiSH*, *Rus.Ukr.Eng*, *-HDCLUB*, *-WLH*, *-TVS*, *-TVR*, *-ZZGtv*, *-pia*, *-FCC*, *-ITG*, *-Coveiro*, *SPAROOD*, *-KGB*, *-TVP*, *-$
except-tags = foreign
#download-duplicates = false
```

**Comment by thebigmunch** [comment]
Since you clearly can't follow simple instructions/requests, you're done.
