### ISSUE TITLE
Torrent action options set to 0 or empty string in filter header not being picked up in v2.0.0

### ISSUE THREAD

**Issue by crjs** [autodl-community/autodl-irssi#145]
I have a test filter that I use with the "Don't download" priority set, but after the 2.0 update it doesn't seem to be working anymore. Torrents are being added as normal priority, and therefore they start downloading as soon as they are matched.

Here is my test filter:

[filter TEST]
match-sites = ar, bithdtv, hds, ipt, morethan.tv, ptm, tby, td, tl
rt-dir = downloads
rt-label = TEST
upload-type = rtorrent
max-size = 60GB
rt-priority = dont-download
enabled = false

Cheers.

**Comment by baz357** [comment]
Same here. :( My filter adds certain torrents with "Don't download" status and gives them a label. This *always* worked perfectly, since the update it started to download torrents.

**Comment by thebigmunch** [comment]
Please don't post things in the issue tracker until you know for sure it is a bug. Instead come to the support channel  as directed in the contributing guidelines. And saying "since the update" doesn't help since that doesn't tell me which version you were on before.
