### ISSUE TITLE
2.0.0 bug: "Don't download" is ignored

### ISSUE THREAD

**Issue by baz357** [autodl-community/autodl-irssi#146]
2.0.0 bug: "Don't download" is ignored

I use a "Don't download" filter for certain torrents. Torrents are just added with a label (that's only used for those torrents). Today I opened ruTorrent to find two *downloaded* torrents with that label. Before I updated (from 1.65) this never happened, torrents were always added but not downloaded.

I read the contributing guidelines and hope this is what's required.

**Comment by thebigmunch** [comment]
Sure, because by saying come to the support channel and locking the other issue, I clearly meant open another issue to clutter up the tracker some more...
