### ISSUE TITLE
Cannot Update

### ISSUE THREAD

**Issue by Pingblue** [autodl-community/autodl-irssi#150]
Trying to update through the update button now fails its also the same when trying to update through IRSSI shell.

Rutorrent plugin 2.00
Irssi v0.8.19

10:21 -!- Irssi: You are running autodl-irssi v2.0.1 | autodl-trackers v202
10:21 -!- Irssi: Bugs and Requests: https://github.com/autodl-community/autodl-irssi/issues
10:21 -!- Irssi: Help and Discussion: http://discord.autodl.community / #autodl-community on irc.p2p-network.net
10:21 -!- Irssi:  ERROR:  Could not check for autodl updates: Error getting update info: HTTP/1.1 403 Forbidden
10:21 -!- Irssi:  ERROR:  Could not check for trackers updates: Error getting update info: HTTP/1.1 403 Forbidden

**Comment by thebigmunch** [comment]
This is a support issue, so it doesn't belong here. It's also not one I can reproduce.
