### ISSUE TITLE
Support for Fast Resume.

### ISSUE THREAD

**Issue by ne0ark** [autodl-community/autodl-irssi#151]
Can you please consider adding an option for Fast Resume per filter.

**Comment by thebigmunch** [comment]
Is that something you can send through the XML-RPC interface? Is that already possible through the rt-commands option for the rtorrent action?

Doesn't seem like there's much reason to add any specific option no matter the case.

**Comment by ne0ark** [comment]
Don't think you can send it through XML-RPC. Rutorrent support for it: https://github.com/Novik/ruTorrent/search?utf8=✓&q=fast+resume&type=

This is Perl script: https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent_fast_resume.pl

A script might have to modify the .torrent file before its sent to rtorrent.

**Comment by thebigmunch** [comment]
Then that's a no.
