### ISSUE TITLE
Request: Censor AnimeBytes passkey from AnnounceParser.

### ISSUE THREAD

**Issue by KurtzPT** [autodl-community/autodl-irssi#152]
At the moment, when there's an announce of a release, autodl-irssi does not censor the passkey from the torrentUrl.

URL format:
`https://animebytes.tv/torrent/<torrentid>/download/<passkey>`

**Comment by thebigmunch** [comment]
You'll have to be more specific. By default, it wouldn't output the download URL.

Are you talking about ``advanced-output-sites`` output or are you talking about the ``output-level`` and/or ``debug`` output?

**Comment by KurtzPT** [comment]
Sorry, I'm talking about the advanced-output-sites.
