### ISSUE TITLE
Authkey for gazelle

### ISSUE THREAD

**Issue by Empornium** [autodl-community/autodl-irssi#153]
Gazelle cycles users authkey every fortnight and doesn't actually check them when downloading a torrent file (it checks if an authkey parameter has been passed but doesn't check its validity). As such Empornium intends to remove authkey from torrent links in a future update and would like to do so without breaking compatibility with AutoDL-irssi.

**Comment by thebigmunch** [comment]
So, as far as autodl-irssi is concerned, it should be as simple as removing the ``<gazelle_authkey/>`` directive and ``authkey`` param from the ``torrentUrl`` from the tracker file. As for users, they would have to remove the authkey setting from the Empornium tracker block in their config.

The latter is the part that will be disruptive to users and not something I can do anything about.

**Comment by Empornium** [comment]
What would happen if they didn't remove that? Would AutoDL simply keep on putting an authkey parameter in the query string (we could deal with that easily)?

**Comment by thebigmunch** [comment]
As far as I can remember, things would work. They'd just get error messages about the unknown tracker option in their config.

> Would AutoDL simply keep on putting an authkey parameter in the query string (we could deal with that easily)?

That wouldn't be viable, short of you simply not removing authkey from torrent links. While I think it might work for existing users, these tracker file directives are used to populate the ruTorrent tracker settings dialog. If the authkey directive was removed from the tracker file, new users wouldn't be able to set it. In turn, an error would arise when the tracker file tries to build the ``torrentUrl`` without an authkey set.
