### ISSUE TITLE
Add more options to max-downloads-per

### ISSUE THREAD

**Issue by ngnh** [autodl-community/autodl-irssi#159]
You can set amount of downloads per hour or days. But not amount of downloads per 3 hours, 6 or 12 hours. That would be a nice option.

**Comment by thebigmunch** [comment]
I don't really see this as being a benefit outside buffer/ratio farming, which is a terrible thing people shouldn't be doing. But, if you have a reason outside that, feel free to post it.

Even if you had a good reason, I'm not likely to spend any time on it myself. And 'Help Wanted' issues never actually get any help. So, I wouldn't expect this to get anywhere at all unless you're willing/able to work on it yourself.
