### ISSUE TITLE
Unix socket support / configurable host

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [autodl-community/autodl-irssi#160]
Unix socket support to handle communication between rutorrent plugin and autodl-irssi. Goal is to allow autodl-irssi to run on separate host than rutorrent (e.g. docker images with only 1 process).

**Comment by thebigmunch** [comment]
I forgot this existed. But, no, I'm not adding this.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
This workaround should fix it (I think) for those trying to connect an instance of rutorrent on different host than autodl-irssi 

`sed -i "s|use constant LISTEN_ADDRESS => '127.0.0.1';|use constant LISTEN_ADDRESS => 'RU---IPADRESS';|g" ~/.irssi/scripts/AutodlIrssi/GuiServer.pm
sed -i 's|$rtAddress = "127.0.0.1$rtAddress"|$rtAddress = "RU---IPADDRESS$rtAddress"|g' ~/.irssi/scripts/AutodlIrssi/MatchedRelease.pm
sed -i 's|my $scgi = new AutodlIrssi::Scgi($rtAddress, {REMOTE_ADDR => "127.0.0.1"});|my $scgi = new AutodlIrssi::Scgi($rtAddress, {REMOTE_ADDR => "RU---IPADDRESS"});|g' ~/.irssi/scripts/AutodlIrssi/MatchedRelease.pm
sed -i 's|if (!@socket_connect($socket, "127.0.0.1", $autodlPort))|if (!@socket_connect($socket, "IRSSI---IPADDRESS", $autodlPort))|g' ~/www/"$(whoami)"."$(hostname -f)"/public_html/rutorrent/plugins/autodl-irssi/getConf.php`

Where "RU---IPADDRESS": rutorrent, and "IRSSI-IPADDRESS": irssi. 

Might help some other souls if on wiki? 

(I use containers to throw up more instances of rtorrent when it reaches ca 1500 torrents. How do you cope with 10k torrents without containers/multiple instances?)
