### ISSUE TITLE
Possibility to skip the actual downloading

### ISSUE THREAD

**Issue by phihub** [autodl-community/autodl-irssi#162]
I use autodl-irssi to feed sonarr and let sonarr do the actual filtering. The downside to this is, that autodl-irssi actually downloads the torrent files. But I don't actually need this, cause if the file matches sonarr would pick it up again. 

So what I am asking is an option maybe in preferences in the action tab to just skip the downloading and just feed the parsed stuff.

**Comment by SteveMalso** [comment]
Are you using the "run program" .torrent action?

**Comment by phihub** [comment]
Yes. I am using a script that triggers Sonarr. autodl downloads the file but if Sonarr decides to download the release it would download the torrent file anyway.

**Comment by SteveMalso** [comment]
Modify this script:
https://github.com/autodl-community/autodl-irssi/blob/35957c4258a28d467974c93155a0a1e9a2b599a4/AutodlIrssi/MatchedRelease.pm

by adding a return statement before the code that downloads the torrent in the function relating to the "run program" action. You can see how I managed to do it with the "rtorrent" action here.

http://www.torrent-invites.com/seedbox-tutorials/302161-autodl-irssi-enhancement-check-imdb-rating-disk-space-b4-downloading-torrent.html

**Comment by phihub** [comment]
Ok I should have been more specific I guess. Would I would like to have is a possibility to skip downloading the ".torrent"-File. This happens way before your missing return statement.

**Comment by SteveMalso** [comment]
Gotcha.

Assuming this is your script
https://github.com/Zymest/autodl-curl-sonarr

 You can try adding the following code to line 228 of MatchedRelease.pm.
`bash /path/to/script '$self->{ti}{torrentName}' '$self->{downloadUrl}'`;
return;

**Comment by thebigmunch** [comment]
Yeah, this has been asked many times. And it just isn't going to happen in autodl.

**Comment by phihub** [comment]
@SteveMalso Thank you. Intead of your approach I added in the lines 

$self->_runProgram();
return;

Thank you for the hint.

**Comment by fryfrog** [comment]
@thebigmunch, if someone else did the work to make it happen in a way acceptable to you, would you merge a pull request for this feature?

**Comment by xelra** [comment]
Yes, please.

Accumulating all these torrent files for no purpose is just something that is wrong.

**Comment by fryfrog** [comment]
This whole "solution" is dumb, but putting it after the `startTime` seems to be a *little* less dumb. And here it is as a `diff`, so placement is easier to understand if line numbers change.

```
--- git/autodl-irssi/AutodlIrssi/MatchedRelease.pm	2019-06-25 12:26:17.667563996 -0700
+++ /var/lib/autodl/.irssi/scripts/AutodlIrssi/MatchedRelease.pm	2019-06-25 13:12:22.612778514 -0700
@@ -231,6 +231,11 @@
 		$self->{httpRequest}->setFollowNewLocation();
 	}
 	$self->{startTime} = gettimeofday();
+
+	# Added to prevent download of .torrent files, short circuit everything.
+	$self->_runProgram();
+	return;
+
 	$self->{httpRequest}->sendRequest("GET", "", $self->{downloadUrl}, $self->{ti}{httpHeaders}, sub {
 		$self->_onTorrentDownloaded(@_);
 	});
```

**Comment by DFDC** [comment]
This is an issue that may be worth investigating. Several sites that AutoDL works with take issue with downloading every single torrent file.

**Comment by fryfrog** [comment]
Just apply the above patch, a better solution would require quite a bit more work.

**Comment by thebigmunch** [comment]
> This is an issue that may be worth investigating. Several sites that AutoDL works with take issue with downloading every single torrent file.

It doesn't download every single torrent file. autodl only downloads a torrent if a filter matches everything but size. If you don't filter based on size, that means it only downloads on matches. If you're using a filter that is matching every single torrent file, then those trackers should be talking to its users about not doing that.
