### ISSUE TITLE
bug? path names are suddenly case sensitive

### ISSUE THREAD

**Issue by baz357** [autodl-community/autodl-irssi#164]
Hi,

I noticed that since about 3 weeks ago, path names are suddenly case sensitive. (I'm sure this wasn't the case before.) When autodl adds a torrent named "Example.2018" from one torrent site, and it then adds the same torrent but named "example.2018" from another torrent site, a SECOND folder is now being created!

That causes me to download the same content twice, wasting HD space and hurting my site ratios.

**Comment by thebigmunch** [comment]
It sounds like you're talking about the torrent client downloading, which has nothing to do with autodl.
