### ISSUE TITLE
Could not check for autodl updates: Error getting update info: HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by maddogeat** [autodl-community/autodl-irssi#167]
There is rate limit on how much times per hour autodl-irssi can check for new version ?

It is 60 requests per hour limit per IP: 
```
curl -s -i https://api.github.com/repos/autodl-community/autodl-irssi/releases/latest | grep ^X-Rate
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1540069724
```
More details about limits:
https://developer.github.com/v3/#rate-limiting

**Comment by thebigmunch** [comment]
Not sure what you filed this issue for; it's not a bug, a feature request, or anything actionable. I'm well aware of the limits. The update check interval is 24 hours. It'd be odd for there to be 60 update checks in the same hour on the same IP without some mitigating circumstances completely out of the scope of autodl-irssi.
