### ISSUE TITLE
Regex filter is not working properly when using modifiers

### ISSUE THREAD

**Issue by walterdevos** [autodl-community/autodl-irssi#169]
**Description:**
Regex filter stops working when adding modifiers.
A modifier seems to be in place already, as filter is always case insensitive.
This behavior is not documented.

**Replicate:**
```
[filter @test]
match-releases = /.*h264.*/i
match-sites = t1,t2,t3
upload-watch-dir = /somebox/downloads/watch/
upload-type = watchdir
use-regex = true
```
**observed result:** didn't match anything
**expected result:** should match h264 and H264

```
[filter @test]
match-releases = .*H264.*
match-sites = t1,t2,t3
upload-watch-dir = /somebox/downloads/watch/
upload-type = watchdir
use-regex = true
```
**observed result:** Irssi: Matched Some Program S02E03 720p WEB **h264**-sOmEgroUp in TV :: Episodes HD (@test), SomeTracker
**expected result:** should not match h264 , cause I didn't modify for case insensitivity. 

(names are obfuscated)

Suggested solutions: Change filter code so it can be tested against perl regex rules, or ad the exeptions to the documentation. 

thanks for all your work! <3

**Comment by thebigmunch** [comment]
The ``//i`` is language-specific syntax for using regex, not regex itself. Just use the regex. Also, all matching is case-insensitive.
