### ISSUE TITLE
Unraid container of rutorrentvpn won't connect to irc, no monitoring at all.

### ISSUE THREAD

**Issue by Turbo123T3** [autodl-community/autodl-irssi#171]
Hello, I have been using a container of rutorrent under Unraid that supports direct VPNing of the container. It works with no issues at all, however I have decided I'd like to monitor in irc for making my life a bit easier. However when I activated autodl-irssi within the container it shows everything just fine except when I add an irc announce server it doesn't even try to join. I've used autodl-irssi before and have set it up in rutorrent before for monitoring. It isn't popping up any errors or anything.  When adding an irc server/channel it shows this http://prntscr.com/m43jn0 - It doesn't show monitoring or anything.

I also have checked multiple servers/channels and none of them work however on other seedboxes it works just fine.

**Comment by thebigmunch** [comment]
The issue tracker is for bug reports and feature requests only, not for support.
