### ISSUE TITLE
autodl listen to irssi channel but can't match/download torrents

### ISSUE THREAD

**Issue by titooo7** [autodl-community/autodl-irssi#173]
**Screenshot of the log here:** https://imgur.com/a/tTSmZtt

**Error message:**

"HttpRequest::_callUser: Undefined subroutine
&AutodlIrssi::MatchedRelease::sha1" reffering to MatchedRelease.pm line 279

PS: I installed autodl-irssi alongside a docker container but other people with the same install can use it without issues

**Comment by thebigmunch** [comment]
The issue tracker is for bug reports and feature requests only, not for support.
