### ISSUE TITLE
Macros remove dot with creating folders

### ISSUE THREAD

**Issue by From2750** [autodl-community/autodl-irssi#174]
I hope somebody can help with a little problem i have about creating new folders for new series with Macros.
I have this to my save folder. 
*/private/Media_Library/TV_Shows/$(Name1)/Season$(Season2)/
The problem is, when is save a new show, ex, Proven.Innocent.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb

it's remove dot.

so my marcos wil save what i tell it to save and create Name/season/files, thats good .
but then it name it Proven Innocent and not Proven.Innocen
is give me many problems when i want to do some commands on Linux,
like 
cd
ffmpeg
scr
and much more, its there a way to keep dot?

**Comment by thebigmunch** [comment]
The issue tracker is not for support.
