### ISSUE TITLE
Add more options to max-downloads-per

### ISSUE THREAD

**Issue by Experien1985** [autodl-community/autodl-irssi#175]
Hi :) great work with autodl-irssi!

I would like to have more options in **maximum download per**, imagine if I download a release in 01\07\2019 at 01:22 and a new release comes in 07\07\2019 at 23:59 or even 08/07/2019 at 00:40, this would be less than a week and I will miss this release, i would like to set it to 4/5/6 days at will. 

Is it possible?

**Comment by thebigmunch** [comment]
I'm not going to add that functionality. If it's a TV series, you're probably better off trying the ``smart-episode`` option anyway.

**Comment by Experien1985** [comment]
The smart-episode download the same episode again, only filter for older ones, and i'm not sure but i think it only filter if exact same release.
