### ISSUE TITLE
[Feature Request] Set environmental variables for exec action

### ISSUE THREAD

**Issue by mvastola** [autodl-community/autodl-irssi#177]
A small feature request:
Would it be possible to -- in addition to macros -- make all those properties available as environmental variables to the external command if the `exec` action is used? 

Obviously it's possible to just have each macro in its own argument to the external command, but it would be cleaner and simpler to allow access via the environment. This would obviously also be backwards compatible so there wouldn't be compatibility issues.

Thanks!

**Comment by thebigmunch** [comment]
Seems kinda pointless to me. With the exec option, you could easily just make them available as environmental variables yourself in whatever you choose to exec.

**Comment by mvastola** [comment]
@thebigmunch, Yes you can do it another way, but it somewhat less robust if other variables are added later on, and makes config files more complicated. IMHO, just because there's an alternate, more complex way to achieve something shouldn't mean it's not worthwhile to add a feature to make it easier.

I would like to apologize though because I did fail to see the message you were only supporting this app for bugfixes. Would you accept a PR if I were to code this addition?

Thanks
