### ISSUE TITLE
[Feature Request] user-defined parameters in torrenturl

### ISSUE THREAD

**Issue by 1kevin335200** [autodl-community/autodl-irssi#178]
I want to use my free tokens when file is larger than a specific value, it seems like i just need to add "&usetoken=1" at the end of download url, but i don't find a way to add it in autodl.cfg. How can i achieve this using autodl-irssi? Thanks

**Comment by thebigmunch** [comment]
There isn't a way to do it from the config. And it's unlikely to be implemented as such.
