### ISSUE TITLE
Could not read: SSL: Unknown error code: 5

### ISSUE THREAD

**Issue by DJPolyBi** [autodl-community/autodl-irssi#181]
I have followed all of the guides I have found online so far.

I keep getting this error code:
`Could not read: SSL: Unknown error code: 5`

- I am on a Seedbox running Debian 8.11
- I have tried using Force SSL
- I have tried: 
```bash\
cd\
cd .irssi\
cd scripts/AutodlIrssi\
wget https://raw.github.com/mnechita/autodl-irssi/master/AutodlIrssi/SslSocket.pm -O SslSocket.pm
```

None of these fixes have unfortunately solved my issue.  Any help would be appreciated.  Thank you!

**Comment by DJPolyBi** [comment]
Here is the full error:

`Error downloading torrent file https://<IPT_URL.torrent>?torrent_pass=<my_torrent_pass>. Error: _onReadAvailable ex: Could not read: SSL: Unknown error code: 5`

**Comment by thebigmunch** [comment]
This is a duplicate of #168 which I keep forgetting to re-open.
