### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by flier56** [autodl-community/autodl-irssi#185]
getting  2 errors after updating to autodl-irssi v2.6.0 when clicking on what's new or update in rutorrent

error could not check for autodl updates: update autodl check cancelled
error could not check for trackers updates: update trackers check cancelled

**Comment by flier56** [comment]
did a reinstall fixed it

**Comment by flier56** [comment]
now getting this error after reinstall
could not check for autodl updates: Error getting update info: http/1.1 403 Forbidden
could not check for trackers updates: Error getting update info: http/1.1 403 Forbidden

**Comment by thebigmunch** [comment]
Yeah. I removed the zip file for the 2.6.0 release as there was a change that needed to be a bit different to be properly backward-compatible with older versions of Net::SSLeay. What I get for maintaining a project in a language I don't keep track of : (

Gonna change that zip file and release a bugfix release as well.

**Comment by flier56** [comment]
ok Thanks

**Comment by flier56** [comment]
i cleared cache and it started  working again for now

**Comment by thebigmunch** [comment]
I put up the new zip file, that's why : P

And now I've made a bugfix release. So, if you could update to that and make sure things are working fine again for you, that'd be great.

**Comment by flier56** [comment]
updated to 2.6.1 working so far
Thanks great work

**Comment by thebigmunch** [comment]
I'll try not to derp so hard next time ^_^

**Comment by Cronick** [comment]
Seems like I have the same issue as flier56. As shown on the picture. I get the same error on 2.6.1.
![image](https://user-images.githubusercontent.com/5100210/67883275-14fd4000-fb44-11e9-887f-97a0e7a7d775.png)

**Comment by stadsc** [comment]
This error occurred after auto update to new version 2.6.2

Reinstalled previous version 2.6.1 and its working.
