### ISSUE TITLE
match multiple filters

### ISSUE THREAD

**Issue by ghostserverd** [autodl-community/autodl-irssi#187]
I'm integrating autodl-irssi with sonarr and radarr so I'd like to match against all TV shows and Movies respectively.

My original plan was to set up two filters, one for sonarr and one for radarr

```
[filter sonarr]
upload-type = exec
upload-command = /home/abc/autodl-curl-pvr.sh
upload-args = "sonarr" "$(TorrentName)" "$(TorrentUrl)" "<apikey>"
match-sites = ptm
upload-delay-secs = 30

[filter radarr]
upload-type = exec
upload-command = /home/abc/autodl-curl-pvr.sh
upload-args = "radarr" "$(TorrentName)" "$(TorrentUrl)" "<apikey>"
match-sites = ptm
upload-delay-secs = 30
```

but from what I can tell, a release will only ever match one filter, so that won't work.

Is there a way to match all TV shows for the sonarr filter and all Movies with the radarr filter, or is there a way to match both the radarr and sonarr filters for everything? I trust sonarr and radarr to figure out what to download and what to ignore, so complicated autodl filters probably aren't necessary.

I tried adding `match-categories = TV` and `match-categories = Movies` but that broke the filters completely.

Any options here? The documentation doesn't make it clear whether or not multiple filters can match a single release.

**Comment by thebigmunch** [comment]
The Issue tracker is for bug reports and feature requests only, not support.
