### ISSUE TITLE
when updating irssi and trackerlist, it does not pull the newest tracker file (asgaard)

### ISSUE THREAD

**Issue by Suiziide** [autodl-community/autodl-irssi#193]
Title pretty much sums it up. I see you committed changes to asgaard file, but when i try to update irssi and trackers, it doesn not pull the latest file, it still pulls the old one.. I even tried removing and installing irssi completely.
![image](https://user-images.githubusercontent.com/36533341/76748870-d1feda80-677b-11ea-85bf-451f1d2bd8f0.png)

![image](https://user-images.githubusercontent.com/36533341/76748917-e642d780-677b-11ea-85b6-e417c0ea5d18.png)

**Comment by thebigmunch** [comment]
Because it hasn't been released yet.
