### ISSUE TITLE
Tracker did not match new line

### ISSUE THREAD

**Issue by zdeev** [autodl-community/autodl-irssi#195]
Hi Folks,

Today TorrentLeech has updated their announce by adding a 'freeleech' tag on said torrents. The regex used in the current TorrentLeech.tracker can't handle this. 
https://i.imgur.com/cU8tQoQ.png

Previous line:
New Torrent Announcement: <Movies :: Boxsets>  Name:'Ultimix Mega Collection' uploaded by 'Anonymous' -  https://www.torrentleech.org/torrent/1612965

New line:
New Torrent Announcement: <Movies :: Boxsets>  Name:'Ultimix Mega Collection' uploaded by 'Anonymous' **_'freeleech'_** -  https://www.torrentleech.org/torrent/1612965

A small change to the regex would fix this.

**Comment by adampetrovic** [comment]
This is the wrong repo.

See https://github.com/autodl-community/autodl-trackers/issues/263

**Comment by zdeev** [comment]
Copied.
