### ISSUE TITLE
Add DanishBytes

### ISSUE THREAD

**Issue by erathor82** [autodl-community/autodl-irssi#208]
Verified and working.

Removed link from pastebin, expired.

Added file instead.

[DanishBytes.tracker.txt](https://github.com/autodl-community/autodl-irssi/files/6190238/DanishBytes.tracker.txt)

**Comment by From2750** [comment]
i Think you sould post it here
https://github.com/autodl-community/autodl-trackers/pulls

**Comment by erathor82** [comment]
I read somewhere that it should be posted here, but sure - i'll give it a go.
