### ISSUE TITLE
Tags/releaseTags

### ISSUE THREAD

**Issue by thebigmunch** [autodl-community/autodl-irssi#26]
The ``tags`` variable has bothered me for awhile. I know that Gazelle trackers (possibly others) use the term tag to refer to genres. But, they're just that, genres. In the context of announces, I think of blocks like ``AVI | XViD | WEB-DL | SD | P2P | FastTorrent`` as the tags. Frankly, the original author seemed to as well as these blocks are handled by a local variable ``$releaseTags`` which is used to map the parts to individual filter options. The problem with this is that not all parts of these blocks map to a filter option while possibly being useful for the user to have access to.

The backward compatible option is to just add ``release-tags`` as a filter option and change all the local references in tracker files to global ones. The user would then be able to use this and/or the individual filter options to match based on release tags. The only downside I see to this is possibly the confusion of tags and release-tags for some users.

The incompatible option is to change the ``tags`` filter options to ``genres``. This would require  changing ``tags`` to ``genres`` in all tracker files and open up changing the ``$releaseTags`` references to ``tags``. For the user, this would mean having to make changes to their autodl.cfg. Even if a simple script was provided to do it automatically for them, this would probably not be a smooth transition.

I'm interested in hearing what people think about either option or the idea as a whole.

**Comment by evilsephiroth** [comment]
Well, an option to snatch or exclude by releaseTags would be awesome. Part of tags is extracted in relevant variable(resolution.bitrate,ecc) but others are excluded...
I.E. AnimeBytes has RAW,Unsubbed release tags and excluding on this field it's impossibile.
I've used a workaround in extractTags(AnimeBytes.tracker) to check for RAW* and store in category the result (that is not used on AB).
By doing this, I can exclude unwanted RAW* but I think it's really a dirty hack.

**Comment by thebigmunch** [comment]
Use #88 for any further discussion/tracking.
