### ISSUE TITLE
FTP SSL/TLS support for torrent completion action

### ISSUE THREAD

**Issue by Weyland** [autodl-community/autodl-irssi#3]
I was wondering if it would be possible to add support for FTP SSL/TLS. This way I would be able to have the files transfered to my home server upon completion using the secure protocol. Since security is much appreciated when downloading files from the seed box I would imagine this is a loose end that needs to be fixed.

I tried getting this to work yesterday, but it does not accept the certificate which in turn makes the whole feature return: "530 Have to use explicit SSL/TLS before logging on."

**Comment by thebigmunch** [comment]
This feature request is by far our oldest. It's never really been at the top of my priority list. Along the way I have had 2 people express interest in working on it that never got started. If anyone is willing to give a little love, post here and/or come to the IRC channel.
