### ISSUE TITLE
Complete support for connecting to IRC Bouncers.

### ISSUE THREAD

**Issue by thebigmunch** [autodl-community/autodl-irssi#41]
The initial support for this was rudimentary. It was released in order to get some testing since nobody was responding to the issue on our tracker. This issue will track some of the current limitations and possible solutions.
- [x] Under some conditions, a blank server password prevented connection to some normal IRC servers. A simple conditional will fix this and has already been addressed in my local repo.
- [x] ZNC usually will send a /who list to the status window when you connect with another client. Currently it is doing this almost constantly. Must determine the cause and if there is a solution.
- [ ] Allow multiple connections aka server headers with the same server. This is a more general change that could end up being backward-incompatible.
- [ ] Rewrite AutoConnector to support connecting to the same server multiple times.

**Comment by thebigmunch** [comment]
For anyone interested on where this stands:

This really won't be solved without a significant rewrite of AutoConnector.pm. Currently, servers are connected to autodl-irssi's settings with the only thing that they have in common, the server address. That is why the original design was to have the address as the header; it was the easiest way. The proper solution is probably to bridge the server settings of autodl-irssi with the servers of irssi with an object encompassing both.

It's unlikely that I'll have the time or motivation to take on this task anytime soon (if ever). If anyone is interested in working on it, feel free. I do have the code that allows the server headers to be an arbitrary name in a backward-compatible way to start from, but that's just an ancillary part of the task.

**Comment by 2devnull** [comment]
Was there any takers on adding this support? If not, is it possible to get a list of steps of what needs to be done to get this function working?

**Comment by thebigmunch** [comment]
Nobody has ever even broached the idea of taking this on but me : P

I provided a general explanation above. And, really, it is for the most part just one big step with a lot of tedious fiddling likely. The first step before the big one is adding a separate server header option for address and a backward-compatible way for server headers to be named arbitrarily. Good news is that I've had the code for that since shortly after the initial bouncer support was put in. I can provide this through IRC or e-mail to anyone interested in possibly taking this on.

I, once, quickly slapped something together to see if it was feasible to achieve without creating a super object to link autodl-irssi server options and irssi servers together. I don't think it's the way to go, but I never had the time to fully tinker with it. I can include that code as well through IRC or e-mail.

**Comment by r000d** [comment]
In case someone with the same problem founds this thread: 
As workaround for multiple connections to the same server at least for bnc's on the same host one can use subdomains for each connection, e.g. abc.lvho.st as bind address for a bnc on localhost (lvho.st resolves to 127.0.0.1).
With this I was able to connect multiple times to my bnc and monitor multiple channels on different networks simultaneously.

**Comment by rahul0705** [comment]
do the current changes on master allow monitoring to work? (will it be able to see the correct announce bot?)
