### ISSUE TITLE
Irssi cannot bind to port (gui-server)

### ISSUE THREAD

**Issue by JesseJams** [autodl-community/autodl-irssi#71]
I've installed this but I cannot get irssi to bind to any port on the system, instead I get the following error:

"17:09 -!- Irssi: GUI server disabled. Got error: Could not bind to port 32200: Cannot assign requested address"

where 32200 is whatever port I've put in the autodl.cfg file (and conf.php) when run by root there is the same error. 

any ideas?

**Comment by thebigmunch** [comment]
Can't really help diagnose peoples' systems, and the Issue Tracker is not a place for general help anyway. If you find that it's something in autodl-irssi or autodl-rutorrent causing the issue, please open an issue then.
