### ISSUE TITLE
autodl-irssi Except filters

### ISSUE THREAD

**Issue by FuzijaCZ** [autodl-community/autodl-irssi#73]
Hi all.

I have been having a hard time with autodl-irssi filters, specifically with Except releases or Except tags.

I basically want to NOT download releases that contain: SPANISH and PSYPHER in the name, but anywhere I put this in the Except field, I still get these downloaded.

Here is the snippet from my autodl-irssi:

[filter TV-TL]
match-releases = 12?Monkeys*,2?Broke?Girls*,About?a?Boy*,Allegiance*,Alpha?House*,American?Crime*,Arrow*,Backstrom*,Banshee*,Bates?Motel*,Battle?Creek*,Better?Call?Saul*,Black?Sails*,Blackish*,Bosch*,Brickleberry*,Broadchurch*,Brooklyn?Nine-Nine*,Castle?2009*,Chicago?Fire*,Chicago?PD*,Community*,Constantine*,Continuum*,Crossing?Lines*,Da?Vincis?Demons*,Daredevil*,Defiance*,Downton?Abbey*,Elementary*,Extant*,Falling?Skies*,Fargo*,Forever?US*,Fresh?Off?the?Boat*,Game?of?Thrones*,Gotham*,Grimm*,Halt?and?Catch?Fire*,Hannibal*,Haven*,Helix*,Hell?on?Wheels*,Homeland*,House?of?Cards*,House?of?Lies*,How?the?Universe?Works*,How?to?Get?Away?with?Murder*,Iron?Fist*,Jessica?Jones*,Kingdom?2014*,Last?Man?Standing?US*,Legends*,Longmire*,Luke?Cage*,Luther*,Marco?Polo*,Marry?Me?2014*,Marvels?Agent?Carter*,Marvels?Agents*,Marvels?Daredevil*,Marvels?Iron?Fist*,Marvels?Jessica?Jones*,Marvels?Luke?Cage*,Marvels?The?Defenders*,Mike?and?Molly*,Modern?Family*,Mom*,New?Girl*,Orange?is?the?New?Black*,Orphan?Black*,Outlander*,Peaky?Blinders*,Penny?Dreadful*,Person?of?Interest*,Ray?Donovan*,Reign*,Scorpion*,Sense8*,Shameless?US*,Sherlock*,Silicon?Valley*,Sleepy?Hollow*,South?Park*,Stalker*,Suits*,Supernatural*,The?100*,The?Americans?2013*,The?Big?Bang?Theory*,The?Blacklist*,The?Exes*,The?Fall*,The?Flash?2014*,The?Following*,The?Last?Ship*,The?Leftovers*,The?Messengers*,The?Middle*,The?Mindy?Project*,The?Odd?Couple?2015*,The?Originals*,The?Simpsons*,The?Strain*,The?Vampire?Diaries*,The?Walking?Dead*,The?Whispers*,True?Detective*,TURN*,Two?and?a?Half?Men*,Tyrant*,Undateable*,Under?the?Dome*,Vikings*,Wayward?Pines*
match-sites = tl
resolutions = 720p
download-duplicates = true
rt-dir = /home/xxx/downloads/Incoming/TV
rt-label = TV
rt-priority = high
upload-type = rtorrent
min-size = 100MB
max-size = 4GB
sources = HDTV
encoders = x264
except-tags = SPANISH,PSYPHER
except-releases = SPANISH,PSYPHER

I don't know what else to try, so I am hoping someone would have an idea what to do.

Thanks.

**Comment by thebigmunch** [comment]
The issue tracker is not for general help. Go to the IRC channel for that.
