### ISSUE TITLE
rtorrent action with UNIX sockets is broken

### ISSUE THREAD

**Issue by NickHu** [autodl-community/autodl-irssi#77]
I have my SCGI gateway set to a UNIX domain socket at /srv/rtorrent/.rpc.sock

Rutorrent and rtorrent can communicate fine via this and everything works as expected, and the socket permissions are 666, however when rt-address is set to /srv/rtorrent/.rpc.sock and the action is set to rtorrent I am informed that torrents are being added without issue despite them never reaching rtorrent.

I have enabled rtorrent logging in debug mode and no events are generated when torrents are supposedly added to rtorrent.

**Comment by thebigmunch** [comment]
Just noticed I forgot to respond to this. I've never heard of an issue with sockets on the rTorrent action. It works on my system. As far as I can tell, the XML-RPC call should fail if there was an issue communicating with the socket.

I don't generally provide support for what appears to be local issue, but, if you can determine that it's not just an issue on your system, post your results here.

**Comment by thebigmunch** [comment]
Closing due to lack of response.

**Comment by genghizkhan91** [comment]
I have this same problem. When you use the rtorrent action with a unix domain socket, it just silently fails.

**Comment by genghizkhan91** [comment]
Okay, never mind, turned out to be a systemd issue. If you have both rtorrent and your irssi instance with `PrivateTmp=true` in the service files, then it doesn't work with either unix sockets or with TCP sockets.

**Comment by uggedal** [comment]
Unix domain sockets will also not work when rtorrent and irssi runst as two different users since Perl's `tempfile` creates the file with `0600` permissions.
