### ISSUE TITLE
Corrupted zip archive for autodl 1.54 download on most platforms

### ISSUE THREAD

**Issue by randomessence** [autodl-community/autodl-irssi#79]
Hello,

The latest update to autodl 1.54 and consequent zip file generation at the URL below seems to have resulted in a corrupted zip file that fails to extract on windows and linux but seems ok using the OS X built in.

```
http://update.autodl-community.com/autodl-irssi-community.zip
```

**Comment by thebigmunch** [comment]
Well, worked on Windows for me. But it failed on Linux. No idea why, it's just a copy of autodl-irssi-community-v1.54 which worked fine. Just redid it, and it seems to be fine now.

**Comment by randomessence** [comment]
I can confirm it now works for me.

Thank you.
