### ISSUE TITLE
Make HttpRequest._getRetryTimeout configurable

### ISSUE THREAD

**Issue by phene** [autodl-community/autodl-irssi#85]
With the rise of DDoS attacks on trackers, many have started using services meant to throttle automated requests by delaying the response (like CloudFlare). The hard-coded 2 seconds is hardly enough time to fully download a torrent file. It would be great to expose this timeout so that it can be configured for longer request durations.

**Comment by thebigmunch** [comment]
That isn't anything like how the retries work: https://github.com/autodl-community/autodl-irssi/wiki/Options-Header#download-retry-time-seconds

**Comment by phene** [comment]
That's the interval between retries, not the timeout length between connection attempt and data received.

**Comment by thebigmunch** [comment]
> That's the interval between retries, not the timeout length between connection attempt and data received.

And that's exactly what _getRetryTimeout is used for in the code. It's only ever used in _retry which is called when some kind of error occurs with an HTTP request.

**Comment by phene** [comment]
How can I increase the timeout for an individual HTTP request? I'm
currently getting HTTP timeouts when autodownloading via these scripts, but
I have no issue whatsoever downloading on the same host with curl and wget.

**Comment by thebigmunch** [comment]
Make sure Perl, Perl libs (specifically Net::SSLeay), and openssl are updated on your server. This could easily be an issue related to adding SNI support in the latest version and having outdated libs. I've never heard of anyone else having any issues for any other reason. What you've mentioned doesn't really sound like a plausible explanation.
