### ISSUE TITLE
Match Release Groups not working

### ISSUE THREAD

**Issue by renzzla** [autodl-community/autodl-irssi#87]
Hi, I'm running 1.54 but am having problems trying to restrict a filter to only a release by a particular group. This is for a TV show, so I have a filter called "The Last Ship" and under "TV/Movies" tab I have "TV Show/Movie" set to "The Last Ship*" (no quotes). Under the "P2P" tab, i set "Match release groups" to "DIMENSION" (again, no quotes) but it doesn't match when the release is announced.

Is the new Match Release Groups filter working? Note, I only have access to RUTorrent, I cannot SSH to the server and have no direct access to the config or log files.

Thanks

**Comment by thebigmunch** [comment]
Use the IRC channel for support. Also, you're missing key details like the tracker.
