### ISSUE TITLE
Support for Collages in Gazelle tracker

### ISSUE THREAD

**Issue by notKuro** [autodl-community/autodl-irssi#94]
Hi,

is it currently possible to create a filter in autodl to download all torrents added to a specific Collage (Collages in the WhatCD [Gazelle tracker](https://github.com/WhatCD/Gazelle)) ?

If so, how?
And if not, please consider adding it.

The reason i'm asking is because torrents in a Collage often have different tags and categories, so you can't create a filter based on that.

**Comment by thebigmunch** [comment]
If it's not in an announce, it's not going to be supported.
