### ISSUE TITLE
Add ability to add torrents directly from the autodl-irssi log pane

### ISSUE THREAD

**Issue by WG47** [autodl-community/autodl-irssi#95]
If I see a torrent appear on a site in the autodl-irssi pane, it'd be nice to be able to click the release name and have the torrent automatically retrieved from the torrent site instead of having to open the site in another tab and download the file.

**Comment by thebigmunch** [comment]
1. That's the ruTorrent plugin, not autodl-irssi itself.
2. That is way out of scope. The entire purpose of autodl-irssi is to automatically download torrents based on rules you provide.
