### ISSUE TITLE
wiki edit

### ISSUE THREAD

**Issue by randomessence** [autodl-community/autodl-irssi#96]
https://github.com/autodl-community/autodl-irssi/wiki/Manual-Installation

I would like to propose a modification to this command:
~~~
curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
~~~

The following command is noticeably shorter and consistently accurate, whilst also being easily customised to be very specific.

~~~
wget -O autodl-irssi.zip $(curl -sL http://git.io/vlcND | grep 'browser' | cut -d\" -f4)
~~~

This command can be quite easily customised to be very specific without really adding any much complexity to the command by editing the grep regex.

~~~
wget -O ~/autodl.zip $(curl -sL http://git.io/vlcND | grep 'browser.*autodl' | cut -d\" -f4)
~~~

Credits: 

http://stackoverflow.com/a/29503623

**Comment by thebigmunch** [comment]
Length != complexity. It's bad enough that the only portable solutions aren't proper ways to parse JSON. It relies on an API response I have no control over, so making it as explicit as possible is best. If you add the ``--quiet`` argument to your command (as in the current one), use the full ``browser_download_url`` field name to be explicit, and rewrite the current one with the same kind of syntax, the length difference isn't quite as significant either:

```
wget --quiet -O autodl-irssi.zip $(curl -sL http://git.io/vlcND | grep 'browser_download_url' | cut -d\" -f4)
wget --quiet -O autodl-irssi.zip $(curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)'))
```

The current command also future-proofs itself for the possibility of multiple files being attached to releases by matching the release archive naming scheme.

**Comment by randomessence** [comment]
With no control over the api there I can't see how it can be specific or future proof, there is using what is available with api v3 until v4 arrives and adapting if required.

I don't think there is anything inherently wrong with your version, in fact I think it was a good idea, just the length could maybe be improved and this is simply a conversation. Here is a very specific version for your current scenario with `-q` instead of `--quiet`

~~~
wget -qO autodl-irssi.zip $(curl -sL http://git.io/vlcND | grep 'browser_download_url' | cut -d\" -f4)
~~~

Still a littler shorter.

~~~
curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
~~~

**Comment by thebigmunch** [comment]
Again, it's not necessarily about being the shortest it can be; it's a simple copy/paste anyway.

I gave a specific case that it is future-proof for, which was not the API changing. The command you suggest simply doesn't support the possibility that I may, in the future, add multiple files to a release. And future-proofing for that part helps with all the 3rd-party guides and wikis that will just copy/paste the command given in this wiki and probably not be as quick to update if that specific case changes.

**Comment by randomessence** [comment]
I did understand what said. With yours using `-q` and mine being very specific they length is not so much different. My last act of defiance.

~~~
wget -qO autodl-irssi.zip $(curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)')
~~~

I'll accept your final word on the matter and consider it settled. Maybe someone will be inspired to craft a better version. Thank you for the work on this project.

**Comment by randomessence** [comment]
Then there is this. Only question is whether getting the filename from the URL is better than setting it manually. I am on the fnece about that one.

~~~
curl -sLO $(curl -sL git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | cut -d\" -f4)
~~~
