### ISSUE TITLE
Create new version

### ISSUE THREAD

**Issue by RobinHoutevelts** [autodl-community/autodl-irssi#97]
Hi,

A lot of PR's have been merged on [autodl-trackers](https://github.com/autodl-community/autodl-trackers/) since Oct 1st yet no new release of autodl-irssi was made.

The wiki has instructions on how to download the latest autodl-irssi version, but that's useless if no new versions are released.

Could you create a new version `v1.7` that has all the latest tracker-updates from [autodl-trackers](https://github.com/autodl-community/autodl-trackers/) ?

Edit:
Now we're here, I do think we could fix the *real* issue. The Wiki.
It's too bad GitHub doesn't allow us to send PR's for a wiki so I have to put it in this issue:

Replacing 
```
curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
```
With

```
wget --quiet -O autodl-irssi.zip https://github.com/autodl-community/autodl-irssi/archive/master.zip
```

That way people always pull in the latest `master` branch. Because right now new users are **months** behind. Even tho the `master` branch is reasonably up to date.

Regards,
Robin Houtevelts

**Comment by thebigmunch** [comment]
Dunno why you're posting about the trackers in the autodl-irssi. They are completely separate repos and have separate updates (aka trackers will update without an autodl-irssi update).

As for that command change, the master branch is never ahead of the latest tag/release save for documentation-only changes; the devel branch of each repo is where development happens. Also, the zipball created automatically by GitHub contains all source files while the release archives leave out files not needed for end users that would just clutter their file system.

PS The last trackers release was about a month ago on [December 2nd](https://github.com/autodl-community/autodl-trackers/releases/tag/community-v251).
