### ISSUE TITLE
Error on update check

### ISSUE THREAD

**Issue by 2devnull** [autodl-community/autodl-irssi#98]
Seems like this change to 1.60:

> Change updater to use GitHub's Releases API.

is causing and error to update to 1.61. Anyone else having this issue from the ru gui?

Didn't have an issue going from the previous version to 1.60.

**Comment by thebigmunch** [comment]
No, GitHub being down for a couple hours last night was causing the error.

**Comment by 2devnull** [comment]
I am trying to update now and it is not updating. Is this issue with GH still occurring?

**Comment by thebigmunch** [comment]
You've yet to actually give the error you're actually getting.

**Comment by thebigmunch** [comment]
Also, this is an issue tracker, not a place to get support. Please go to the IRC channel instead.
